[package]
name = "physx_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.22.0"
once_cell = "1.17.0"
physx = { version = "0.16.0", features = ["glam"] }
physx-sys = "0.8.1"
